### ISSUE TITLE
Substituir termo "EvCash" por "Evo" na documentação

### ISSUE THREAD

**Issue by joaoscalett** [EvoluServices/transaction-proposal#14]
Faz algum tempo que a aplicação [EvCash ](https://www.evcash.com.br/) foi rebatizada para [Evo](https://sejaevo.com.br/).

No entanto, na [documentação da API](https://evoluservices.github.io/transaction-proposal/#iniciar-uma-transa-o) ainda há referências ao nome ou site antigos.

**Comment by marcelo92** [comment]
Bem observado, já foi criada uma branch e o pull request será feito em breve. Obrigado.
