### ISSUE TITLE
Adicionar nomes dos métodos nas seções correspondentes

### ISSUE THREAD

**Issue by oliveiragabriel07** [EvoluServices/transaction-proposal#4]
Atualmente, os nomes dos métodos podem ser encontrados apenas na seção "Visão Geral". Seria interessante adicionar os nomes dos métodos também nas seções que descrevem cada um deles:
* Autenticação
* Iniciar Transação
* Remover Transação

**Comment by marcelo92** [comment]
Os métodos de requisição (POST/DELETE) e as URLs foram colocadas logo no início de cada seção para facilitar a consulta
