### ISSUE TITLE
Exemplos vs Texto - Página de docs

### ISSUE THREAD

**Issue by oliveiragabriel07** [EvoluServices/transaction-proposal#5]
Na página da documentação (https://evoluservices.github.io/transaction-proposal) muitas vezes o conteúdo aparece apenas no exemplo tornando a compreensão mais difícil.

Exemplo: Autenticação > Header:

> Header
> É necessário especificar no header o tipo de conteúdo enviado no body da requisição.

O header que deve ser introduzido na requisição não está presente no texto. É necessário inferir a partir do exemplo do lado direito:
> Content-Type application/json

**Comment by marcelo92** [comment]
Acrescentei essas informações na descrição do header tanto na autorização quanto no inicio de transação, faltou algum lugar?
