### ISSUE TITLE
Autenticação - Parâmetros Body

### ISSUE THREAD

**Issue by oliveiragabriel07** [EvoluServices/transaction-proposal#6]
Na tabela de parâmetros do Body não é mencionado que as propriedades devem estar contidas em um objeto "auth":
![2017-05-02_10h57_59](https://cloud.githubusercontent.com/assets/1162896/25620951/5fb8d808-2f26-11e7-814e-e0630f39f7a1.png)

Esta informação consta apenas no exemplo:
![2017-05-02_10h58_35](https://cloud.githubusercontent.com/assets/1162896/25620916/4d9e0530-2f26-11e7-95ee-22212b301ac1.png)

**Comment by marcelo92** [comment]
Tem razão, pus na descrição logo antes da tabela
